// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const UPDATE_COURSE_NAME = 'UPATE_COURSE_NAME';
